### ISSUE TITLE
Home Assistants goes into Safe mode

### ISSUE THREAD

**Issue by jstelten** [basnijholt/home-assistant-config#20]
After installing HACS, the IOS theme, changed the configuration and rebooted the system. It's starts in safe mode.

My config is:

```
# Configure a default setup of Home Assistant (frontend, api, etc)
default_config:
frontend:
  ... # your configuration.
  themes: !include_dir_merge_named themes
  ... # your configuration.
  
# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
```
