### ISSUE TITLE
Apple Watch: temperature report - all on one line

### ISSUE THREAD

**Issue by jgeorge1983** [basnijholt/home-assistant-config#39]
Not sure if I'm doing something wrong here, but when I run the action it appears on one line/block of text rather than a newline per temperature?  Also when I run the action I have to click on the notification to bring it up? not sure if thats an update to how actions run or a setting I have missed?  See below for my code:

```
alias: "Apple Watch: temperature report"
description: ""
trigger:
  - platform: event
    event_type: ios.action_fired
    event_data:
      actionName: Temperature report
condition: []
action:
  - variables:
      iphone: >-
        notify.mobile_app_{{ trigger.event.data.sourceDeviceName.replace('-',
        '_') }}
  - service: "{{ iphone }}"
    data:
      title: Temperature
      message: >
        Living room: {{states('sensor.living_room_thermostat_current_temperature') }}°C
        Bedroom: {{ states('sensor.temperature_bedroom_temperature') }}°C Spare
        Spare Bedroom: {{ states('sensor.temperature_spare_bedroom_temperature') }}°C
        Thermostat: {{ state_attr('climate.living_room_thermostat', 'temperature') }}°C
        Outside: {{state_attr('sensor.temperature_outside_temperature', 'temperature') }}°C and it's {{ states('weather.home') }}
mode: parallel
```
