### ISSUE TITLE
fix template-entity-row

### ISSUE THREAD

**Issue by basnijholt** [basnijholt/home-assistant-config#5]
This keeps changing back
```yaml
entities:
  - entities:
      - icon: 'mdi:currency-eur'
        name: >
          {% set kwh = state_attr('switch.dishwasher', 'today_energy_kwh') |
          float %} {% set cost_today = 0.1979 * kwh %} Today used {{ kwh }} kWh
          and cost €{{ cost_today | round(2) }}.
        type: 'custom:template-entity-row'
    head:
      entity: binary_sensor.dishwasher
      name: Dishwasher
      secondary: >
        {% set on_for = as_timestamp(now()) -
        as_timestamp(states('input_datetime.dishwasher_started')) %} {% set
        off_for = as_timestamp(now()) -
        as_timestamp(states('input_datetime.dishwasher_done')) %} {% if
        states('binary_sensor.dishwasher') == 'on' %} Has been on for {{ (on_for
        / 60)|round(0) }} minutes. {% else %} Has been off for {{ (off_for /
        3600)|round(1) }} hours. {% endif %}
      state: >
        {% if is_state('binary_sensor.dishwasher', 'on') %} {{
        states('sensor.dishwasher_watts') }} Watt {% else %} Off {% endif %}
      type: 'custom:template-entity-row'
    type: 'custom:fold-entity-row'
  - entities:
      - icon: 'mdi:currency-eur'
        name: >
          {% set kwh = state_attr('switch.washing_machine', 'today_energy_kwh')
          | float %} {% set cost_today = 0.1979 * kwh %} Today used {{ kwh }}
          kWh and cost €{{ cost_today | round(2) }}.
        type: 'custom:template-entity-row'
    head:
      entity: binary_sensor.washing_machine
      name: Washing machine
      secondary: >
        {% set on_for = as_timestamp(now()) -
        as_timestamp(states('input_datetime.washing_machine_started')) %} {% set
        off_for = as_timestamp(now()) -
        as_timestamp(states('input_datetime.washing_machine_done')) %} {% if
        states('binary_sensor.washing_machine') == 'on' %} Has been on for {{
        (on_for / 60)|round(0) }} minutes. {% else %} Has been off for {{
        (off_for / 3600)|round(1) }} hours. {% endif %}
      state: >
        {% if is_state('binary_sensor.washing_machine', 'on') %} {{
        states('sensor.washing_machine_watts') }} Watt {% else %} Off {% endif
        %}
      type: 'custom:template-entity-row'
    type: 'custom:fold-entity-row'
  - entities:
      - icon: 'mdi:currency-eur'
        name: |
          Today's usage statistics
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          {{ states('sensor.daily_power')|round(2) }} kWh power → €{{
          states('sensor.daily_power_cost')|float|round(2) }}.
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          {{ states('sensor.daily_gas')|round(2) }} m³ gas → €{{
          states('sensor.daily_gas_cost')|float|round(2) }}.
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          €{{ states('sensor.daily_energy_fixed_cost')|float|round(2) }} (fixed)
          + €{{ (states('sensor.daily_gas_cost')|float +
          states('sensor.daily_power_cost')|float)|round(2)}} = €{{
          (states('sensor.daily_gas_cost')|float +
          states('sensor.daily_power_cost')|float +
          states('sensor.daily_energy_fixed_cost')|float)|round(2) }}.
        type: 'custom:template-entity-row'
      - type: divider
      - icon: 'mdi:currency-eur'
        name: |
          {{ as_timestamp(now()) | timestamp_custom('%B') }}'s usage statistics
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          {{ states('sensor.monthly_power')|round(2) }} kWh power → €{{
          states('sensor.monthly_power_cost')|float|round(2) }}.
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          {{ states('sensor.monthly_gas')|round(2) }} m³ gas → €{{
          states('sensor.monthly_gas_cost')|float|round(2) }}.
        type: 'custom:template-entity-row'
      - icon: 'mdi:currency-eur'
        name: >
          €{{ states('sensor.monthly_energy_fixed_cost')|float|round(2) }}
          (fixed) + €{{ (states('sensor.monthly_gas_cost')|float +
          states('sensor.monthly_power_cost')|float)|round(2)}} = €{{
          (states('sensor.monthly_gas_cost')|float +
          states('sensor.monthly_power_cost')|float +
          states('sensor.monthly_energy_fixed_cost')|float)|round(2) }}.
        type: 'custom:template-entity-row'
    head:
      entity: sensor.daily_gas
      name: Energy usage
      secondary: >
        Today {{ states("sensor.daily_power")|round(2) }} kWh and {{
        states("sensor.daily_gas")|round(2)}} m³ gas.
      state: >
        €{{ (states("sensor.daily_gas_cost")|float +
        states("sensor.daily_power_cost")|float +
        states("sensor.daily_energy_fixed_cost")|float)|round(2) }}
      type: 'custom:template-entity-row'
    type: 'custom:fold-entity-row'
show_header_toggle: false
title: Utilities
type: entities

```
